### ISSUE TITLE
Analemma 3D R2

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#1]
## [Analemma 3D](http://ladybug-analysis-tools.github.io/ladybug-web/analemma-3d/)

Latest update: 2016-03-13 / R2
### Features
- 3D plot of Sun azimuth and altitude once an hour for days 1 through 28 of each month. 
- Default latitude and longitude is San Francisco
- Sliders update latitude and longitude of analemma in realtime
- Displays map of location
  - Nine maps styles to choose from
- Buttons available for selected cities
- Midnight highlighted is red. Noon highlighted in green
- Placards indicate the hour of each analemma
- Permalink support
### Issues
- Has math error: noon and midnight analemmas are not opposite each other. 
  - Observe this error when viewing latitudes near Equator
- Map not positioning correctly

_Also [Read Me](http://ladybug-analysis-tools.github.io/ladybug-web/) updated and a few more links of interest added_

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour! I'm not sure how much this will help but analemma should look like this:

![analemma](https://cloud.githubusercontent.com/assets/2915573/13732267/2402298a-e955-11e5-84bb-379d2acf294c.jpg)

Do you think it will be helpful if I generate all the values for San Francisco for example?

**Comment by theo-armour** [comment]
Thanks @mostaphaRoudsari 

The values are not that important. It's the code that I would like to see...

**Comment by mostaphaRoudsari** [comment]
Of course! It's in Python though: https://github.com/ladybug-analysis-tools/ladybug-core/blob/master/ladybug/sunpath.py#L97-L138

**Comment by theo-armour** [comment]
@mostaphaRoudsari Thanks. Will continue tomorrow.
