### ISSUE TITLE
Using the GitHub API to create an organization dashboard

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#10]
![image](https://cloud.githubusercontent.com/assets/547626/13941916/f2b20c50-efa9-11e5-8f4c-cc03e8e3ead9.png)

Hi Team Ladybug

I have started playing around with the GitHub API
## [Ladybug GitHub API Explorer](http://ladybug-analysis-tools.github.io/ladybug-web/ladybug-github-api-explorer/ladybug-github-api-explorer-r1.html)

The read me that appears when you open the link explains a lot.

I am thinking of some kind of dashboard that would be useful as the Ladybug GitHub home page.

If this work is of interest, then I should move the folder to the main github.io repo and continue the effort from there.

Theo

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour! I like the emoji page so much.

What do you see to be the difference between this dashboard and the current github dashboard? or other available resources?

One of the issues that we have encountered using github API for Hydra is that we reach the hourly limit and after that it doesn't work for the next hour! We cache data in case of Hydra so the interface doesn't break because of this.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> What do you see to be the difference between this dashboard and the current github dashboard? or other available resources?

See: https://github.com/ladybug-analysis-tools

I don't find the main GitHub dashboard fun or inviting or informative if you are a new user. And for a returning user, there's no easy way to to know what's new or fresh.

Yes, with much clicking down and much clicking back up you can find thing.

I am interested in exploring new ways of presenting scripts that are embedded deep in large numbers of files and folders with many scripts being updated frequently and many scripts that are stale and nearly smelly.

Here is the next iteration of what I have been working on:

[Ladybug Web Project Explorer](http://ladybug-analysis-tools.github.io/ladybug-web/ladybug-web-via-github-api-r1.html)

Note you have to scroll down quite a ways before you see what is going on. The read me has much more detail.

> > One of the issues that we have encountered using github API for Hydra is that we reach the hourly limit and after that it doesn't work for the next hour! We cache data in case of Hydra so the interface doesn't break because of this.

I assume Hydra is running and on a server.- so all GitHub API calls would be seen to be coming from the single server. In that case, even an authenticated user with a quota in the thousands might well be overwhelmed.

The Project Explorer here runs client-side. Each user establishes a fresh quota just for that user. So I envisage many fewer problems than users running on servers.

**

All of this is work-in-progress - and there's a long ways to go.

I think the main thing is that if we are building stuff in 3D then we must use 3D to the max. Showing 2D images of 3D scripts is - ultimately - a fail.

Theo

**Comment by theo-armour** [comment]
[Ladybug Web Project Explorer R2](http://ladybug-analysis-tools.github.io/ladybug-web/ladybug-web-via-github-api-r2.html)

Adds a content menu top right
