### ISSUE TITLE
Status Update ~ 2016-03-22 ~ there's some there there

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#11]
Maybe we aren't quite 'there' yet, but at least we are getting some buildings visible wherever there is. ;-)

All very R1, The Read Me in [Ladybug Web Shadow Explorer](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-explorer/) has quite a bit more detail.

![image](https://cloud.githubusercontent.com/assets/547626/13975897/85951cf6-f077-11e5-8e41-a278fe8a1cbb.png)
## [Ladybug Web Shadow Core](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-core/)
- A basic engine for calculating and displaying analemmas and sun positions
- Supports any latitude and longitude
- Supports year, month, date, hour, minute date and time
- Loads JSON files from a URL
- Supports permalinks for the above plus
  - Camera position and camera target
  - Various other minor settings

![image](https://cloud.githubusercontent.com/assets/547626/13976133/ed36ea54-f079-11e5-8359-cedfc14c0e08.png)
## [Ladybug Web Shadow Explorer](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-explorer/)
- Two column menu and contents display
  - Menu list files that can be displayed
- Loads Markdown files and converts them to HTML
- Loads JSON files using [Ladybug Web Shadow Core](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-core/)
- Updates sun position in real-time

For details see the Read Me in [Ladybug Web Shadow Explorer](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-explorer/)

![image](https://cloud.githubusercontent.com/assets/547626/13976797/6ce1162a-f080-11e5-9e88-8ca0ec8f7cb7.png)
### Latest update: 2016-03-22 / R10
- Add arcs for 21 of each month
- Add a north arrow

**Comment by mostaphaRoudsari** [comment]
This is beautiful! It's like a dream comes true!
![](https://cloud.githubusercontent.com/assets/547626/13976133/ed36ea54-f079-11e5-8359-cedfc14c0e08.png)

**Comment by theo-armour** [comment]
Hi @mostaphaRoudsari

> > This is beautiful! It's like a dream comes true!

I agree - and for me it's taken a very long time to get there.

When I was at the AA in London - somewhere between 1972 and 1972 - I wrote a paper about an experiment to measure insolation that was a failure. By then, light meters were fairly ubiquitous in cameras. I had the idea that you could point a camera at a standard shade of color and obtain a reading. From this - by using a lookup table - you could approximate how many watts per meter of solar energy this corresponded to. I went to the Royal Academy Library, The Royal Institute of British Architects library and whatever. But did not even come close to sourcing relevant data. Doing research before computers and Internet mostly ended in failure.

So, yes, amazing stuff. 

And even more fun: the code is not difficult. And even geeezers like me may help disrupt things.

No shadow efforts today. I have a visitor from France.

Theo

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour, Inspiring!

Now that we have the sunpath and the geometry there is no reason we can't calculate solar insolation on surfaces. We can caluclate the values for each sky patch and it's a matter of solving vector math which seems to be pretty doable.

BTW in 1972 I was -10 years old if there is such a thing as negative age :D
