### ISSUE TITLE
Status Update ~ 2016-03-31 ~ Calculations Compare

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#15]
![image](https://cloud.githubusercontent.com/assets/547626/14193090/e376ab60-f756-11e5-923b-5bb951f89c7c.png)

Multiple Math Messes.  It's maddening!

Just because it looks good does not mean it is good. Tools that help verify the quality of the data are essential. And you have to start somewhere.
### Update 2016-03-31
- R2
- Compares Agafonkin, Bostock and NOAA
- Nobody agrees on the position of the Sun ;-)
- Structural differences in the code make comparisons difficult

**Comment by mostaphaRoudsari** [comment]
@theo-armour NOAA's algorithm is one of the most accurate available algorithms so I would use that as the base.

**Comment by theo-armour** [comment]
![image](https://cloud.githubusercontent.com/assets/547626/14222443/a8e146ac-f825-11e5-9350-2adab6fb6c7f.png)

@mostaphaRoudsari 

[Calculations Conpare R3](http://ladybug-analysis-tools.github.io/ladybug-web/calculations-compare/)

I think most issues solved. 

So an updated Ladybug Web Solar Calculator might be up tomorrow.

**Comment by mostaphaRoudsari** [comment]
Sounds great! I'm looking forward to it.
