### ISSUE TITLE
Status Update ~ 2016-04-03 ~ Many Updates

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#17]
Too much happened today to think about taking pictures. ;-)

Srarted with: 
[Ladybug Web Shadow Core NOAA](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-core/ladybug-web-shadow-core-noaa-r1.html)
- Uses new solar calculator based on NOAA Solar Calculator
- Bib issue simplified: does not play well with current analemma code
- Fixes will take a lot of re-thinking

So looked again at Bostock code, but the issues include
- Unwanted external dependency on D3
- Twenty lines of complex and opaque code
- Gave up and decided to stay with Agafonkin's SunCalc
- Generally differs with NOAA by a fraction of a degree - s should be OK really
- Then
- Had change of heart and looked into getting rid of Bostock's dependency
- Succeeded

[Bostock Solar Calculator Viewer R5](http://ladybug-analysis-tools.github.io/ladybug-web/bostock-sandbox/bostock-solar-calculator-viewer-r5.html)

Built standalone solar calculator based on Bostock code:  
[Ladybug Web Solar Calculator Bostock Viewer ](http://ladybug-analysis-tools.github.io/ladybug-web/solar-calculator/index.html)
- Also fiddled with and renamed the other solar calculators

Had to verify things are working as they should. Updated Calculations Compare:  
[Calculations Compare](http://ladybug-analysis-tools.github.io/ladybug-web/calculations-compare/)
- Things look good

Let's see how things look with shadows and analemmas:

[Ladybug Web Shadow Core Bostock](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-core/)
- For the most part the code just slipped right in. Except:
- Analemmas are upside down

Well, that gives us something to do tomorrow...

**Comment by mostaphaRoudsari** [comment]
@theo-armour if you think it helps with the development we can leave the accurate calculation for later. We can write a javascript version of the current python code that we have for ladybug.sunpath. It has been validated against NOAA.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> > if you think it helps with the development we can leave the accurate calculation for later. 

Agreed. In many ways, I should just have stayed with SunCalc.js. The difference between it and the NOAA calculations are nearly inconsequential.

On the other hand, I learned much this week by playing with Bostock's and NOAA's code. And much more to the point we are beginning to have code that compares and reports on multiple solar calculation systems.

And even better, all this opens the way to unfinished systems - things that keep on growing and morphing and improving.

> > We can write a javascript version of the current python code that we have for ladybug.sunpath. It has been validated against NOAA.

The more versions the better. The more people can see different ways of doing the same thing, the deeper their understanding will be.

Please do send me a link to the equivalent Python code

**Comment by theo-armour** [comment]
Is this the primary Sun path code you are using?

https://github.com/ladybug-analysis-tools/ladybug/blob/master/ladybug/sunpath.py

**Comment by mostaphaRoudsari** [comment]
@theo-armour, Yes. That is the one.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

The code looks quite readable to me. I think we will have much fun improving and clarifying the code in parallel.
