### ISSUE TITLE
Status Update #2 ~ 2016-04-03 ~ New Home Page 

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#18]
New Home page

[Ladybug Web Project Explorer](http://ladybug-analysis-tools.github.io/ladybug-web/)

Read all about it here:

[Ladybug Web Project Explorer Read Me](http://ladybug-analysis-tools.github.io/ladybug-web#project-explorer-readme.md)

**Comment by mostaphaRoudsari** [comment]
Beautiful!

**Comment by theo-armour** [comment]
Thanks! And, fingers crossed, it's only going to get faster and smoother and more informative
