### ISSUE TITLE
Status Update ~ 2016-04-04 ~ Many more updates

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#19]
Nothing much worth taking a photo of, but a productive day nonetheless.

Besides the files noted below, many of the files in their restive cohorts were also updated

And in other parts of the forest, efforts were made to streamlining the process of bringing in JSON and OBJ files

---
### [Ladybug Web Shadow Core Bostock R2](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-core/)
- Add Ladybug Web Shadow Core Bostock R2
- Analemmas no longer upside down
- Code and variable name logic clean-up 
- Add slide-out hamburger menu
- Add Sun position read-out to menus of all core apps
  - Finding issues with all of them. So it goes
### [Ladybug Web Shadow Explorer Bostock JSON R1](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-explorer/)
- Add ladybug-web-shadow-explorer-bostock-json-r1.html
- Adds sun and position read out
- Code cleanup and multiple small fixes
### [Ladybug Web Shadow Opener Bostock JSON](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-opener/)
- Add Ladybug Web Shadow Opener Bostock JSON R1
- Many small fixes

**Comment by mostaphaRoudsari** [comment]
@theo-armour I tried to update the geometry to a different json file generated by va3c but it didn't work. I know it's still under development but just some feedback.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Good catch. Thanks for checking.

The vA3C files are all Three.js JSON 4.

The scripts here only read Three.js JSON 3 

;-(

But not really. See also today's update.

;-))
