### ISSUE TITLE
Sample 3D Models for test cases

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#20]
It would be a good thing to have access t several dozen different 3D model files that we can uses as test cases and for demos.

I am working on importers for Three.js JSON R3 files and also for OBJ and STL files. Next will be an effort on the up and coming GLTF format

Does anybody have access to 3D models that are nice to look at, have a good amount of 3D-ness about them, and could load reasonably quickly?

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour, What is the scale that you're looking for? A couple of buildings, A single landmark building or an urban scale file? I have [this model](http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Real-time_Radiation_Analysis_with_Ladybug&slide=2&scale=1&offset=0,0) that I can share.

cc: @chriswmackey, @ayezioro

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

You model looks like it would be fun to play with. Good stuff!

Can you create a repo with the title '3d-models' and add the model there?

Once the repo is created, I will add the models I have and they can be used by all the Ladybug apps. Perhaps each file type - json, obj, stl should have its own folder

**Comment by mostaphaRoudsari** [comment]
@theo-armour, sounds good. A quick question: since the geometries are only going to be used by ladybug-web can we create a folder under this repo instead of creating a new repository?

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> since the geometries are only going to be used by ladybug-web ... ?

I hope that many peeps use the models

There is a huge number of 3D models available on the web but almost all - such as 3D Warehouse, Claraio and many more - require you to download models to your hard disk before using them. This is very old school.

For testing and demo purposes, the web needs a repository of 3D FOSS AEC models available to all from CORS-enabled servers such as GitHub

I see a repository of models with adjoining sun path capability being a bright spot on the web. ;-)

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour,

[Here we go!](https://github.com/ladybug-analysis-tools/3d-models) I added the [first model](https://github.com/ladybug-analysis-tools/3d-models/tree/master/models/urban_model_001). I think we should have everyone to create a readme.json file and add a thumbnail for their model which we will use later to make a visual web-based dashboard for them.

**Comment by ayezioro** [comment]
Hi,
I've been following this one with some interest.
I would suggest to add a protocol of what are the formats required (must and could be) and how to create them. Specifically i don't know how to create json files ... (shame on me ...?).
-A.

**Comment by mostaphaRoudsari** [comment]
Hi [Abraham](https://github.com/ayezioro),

@theo-armour will have more in detail suggestions. I think we can start with .obj files and then generate json files later. As you saw up there I started one folder as an example. I can add you to the repository so can take care of adding files.

For exporting to json you can use any of the available plugins for Grasshopper including [spectacles](http://www.food4rhino.com/project/spectacles?ufh) and [iris](http://www.food4rhino.com/project/iris).

Also check out @theo-armour's magic for moving sunpath to the web [1](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-opener/ladybug-web-shadow-opener-bostock-json-r2.html), [2](http://ladybug-analysis-tools.github.io/ladybug-web/multiple-lights/multiple-lights-r2.html#5). Cool! Right? Let us know your thoughts/comments.

**Comment by theo-armour** [comment]
@ayezioro @mostaphaRoudsari 

All good thoughts. Will reply in detail later today - after I finish coding

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> > Here we go! I added the first model. 

Yay and thanks.

> > I think we should have everyone to create a readme.json file and add a thumbnail for their model which we will use later to make a visual web-based dashboard for them.

I added a note to the read me about this

@ayezioro 

> > I would suggest to add a protocol of what are the formats required (must and could be) and how to create them.

Actually, the more models in more formats the better. 

And even more important: what format would you like and would be the easiest to do things with?

Here's a list of the formats the upcoming viewer will support. Many are quite obscure, but you might find one or two that you like.
- amf
- awd
- babylon
- babylonmeshdata
- ctm
- dae
- fbx
- js
- json
- 3geo
- 3mat
- 3obj
- 3scn
- kmz
- md2
- obj
- playcanvas
- ply
- stl
- vtk
- wrl
