### ISSUE TITLE
Status Update ~ 2016-04-05 ~ Nothing Here? Heh heh heh...

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#21]
![image](https://cloud.githubusercontent.com/assets/547626/14303533/5354a27c-fb60-11e5-9017-c2dabab8d6d3.png)

Yup no commits to Ladybug Web today.

All the days efforts were devoted to here:
### [Read Me](http://jaanga.github.io/cookbook-threejs/viewers/#loader-threejs/readme.md)

This script allows you to drag and drop or use the operating system file dialog box to load and display 21 file types.

Loaded files can be zoomed, panned and rotated. The models may be scaled, rotated and positioned.

A simple lighting system add shade and shadows. Some models are zoomed to fit automatically.

And there's more on the way.

If I remember correctly, some of us spent two and a half days a while back - trying to build a 3D model file viewer. Compare and contrast with this one person 8 hour effort.

No don't. Wait until the next release when it's part of Ladybug Web.

**Comment by mostaphaRoudsari** [comment]
Yooohooo! Just tested it and works pretty well with geometry but doesn't apply the materials. Is it supposed to be like this or am I doing something wrong?

Here is the file: https://dl.dropboxusercontent.com/u/16228160/D3TestData/threeD/3D10.0_12.0_24.0_66.0_17.0_2.0_0.0_0.0_0.1.json

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Your file loads just fine in r2. Thank you.

Complicated day.

See 

http://jaanga.github.io/cookbook-threejs/viewers/#loader-threejs/readme.md
