### ISSUE TITLE
Status Update ~ 2016-04-07 ~ Bingo! with cherries on top

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#22]
![image](https://cloud.githubusercontent.com/assets/547626/14370611/aa4bef42-fce4-11e5-8341-2ca6b7515f07.png)
Three.js JSON R3 with textures

![image](https://cloud.githubusercontent.com/assets/547626/14370777/f043dfd6-fce5-11e5-8090-acfce56f0d4a.png)
Three.js JSON R4 ~ having issues with shadows

---

So it's fairly much all working. You can load models locally from your hard disk or online from the web - adjust position, scale and rotation. you can adjust camera location and target. You can set location, date and time and - tada - you can see where the sun is and see the shade and shadow on your buildings. You can save - and test - all your efforts as a permalink that you can send to your colleagues and clients. And the code remains fairly easy, concise and performant.

The primary challenges are met.

That's not to say that it's ready to 'ship'. The UI is ugly and there remain a number of minor issues to be dealt with. 

The drag and drop to load local files is still tricky - and its operation will be explained at a later date.

The sun is beginning to shine...

---
### 2016-04-07
- Add R2
- Add drag-and-drop URL
## Full screen: [Ladybug Web Shadow Core Bostock R3](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-core/)
- Add R3
- Add support for all the Three.js JSON standards
- Fix scaling issues

**Comment by mostaphaRoudsari** [comment]
@theo-armour first screen capture is very nice!

I think I found one minor bug. Toggle ground plane only works the first time. It gives an error on line 288.

``` javascript
            ifr.contentWindow.gridHelper.visible = false;
```

_ladybug-web-shadow-opener-bostock-json-r2.html:288
Uncaught TypeError: Cannot set property 'visible' of undefined_

Finally, isn't it easier to scale and move sunpath instead of the geometry? I imagine cases that the user input a complex mesh and moving or scaling the geometry will be expensive performance wise.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> >  Toggle ground plane only works the first time

Bug fixed. There was a typo. Thanks for the heads-up

> > Finally, isn't it easier to scale and move sunpath instead of the geometry? I imagine cases that the user input a complex mesh and moving or scaling the geometry will be expensive performance wise. 

Excellent thought! It made me jump when I read it.

I am adding it to the wish list and will build a version around this thought.

The reason for not doing this so far is that my dream is to be able to compose multiple elements in the viewer: models, geography, skyboxes etc. But your idea is great for many ordinary use cases.

**Comment by mostaphaRoudsari** [comment]
@theo-armour thanks! #goteam
