### ISSUE TITLE
Status Update ~ 2016-04-09 ~ Zooming ahead

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#23]
![image](https://cloud.githubusercontent.com/assets/547626/14402299/2edad5f0-fde6-11e5-88bf-b09fdbf56a5e.png)
Urban Model 001 in JSON format

---

Today was one of those days where everything you do just works. So you do more and more and more. And then you realize you have added a dozen new things to the list of things to be finished. ;-)

It's all beginning to look OK, but there are still a bunch of minor irritations and flakiness.

With a bit of luck, the next few days should see these being cleared up along with a bunch of models - in JSON and OBJ format - so you can test and get a feel for what is going on/

---
### [Ladybug Web Shadow Core Bostock](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-core/)
- Add send messages to parent
- Add toglle placeMap visibility
- Set default file to urban model 001
- Improve ability to load files
  - Add cast and receive shadows
  - Add two sides
- Add Edges Helpers to R4 files
- Other bits and bobs
### [Ladybug Web Shadow Explorer Bostock JSON](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-explorer/)
- Add link to Shadow Opener to every menu item
- Add messaging from core
- Big revision is in the works elsewhere
### [Ladybug Web Shadow Opener Bostock JSON](http://ladybug-analysis-tools.github.io/ladybug-web/shadow-opener/)
- R3
- Fix Toggle Ground Plane typo. Thanks Mostapha!
- Tighten up menu
- Add sliding 'hamburger' menu
- Remove ability to read Markdown files
- Remove unused 75+ limes of unused code
- Add location.hash capability
- Add Toggle Analemma
- Add Sun light slider
- Add messaging from core
- Set default file to whatever core wants
- Disable zoom if not top window
- And a bunch of other bits and bobs

Also added to the new 3d-models repo a JSON version of Urban Model 001 that is in OBJ format

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour!

Sorry that I wasn't around for a couple of days. I was up in Boston for a number of presentations.

Ladybug shadow opener R4 looks like a production product. I found a couple of bugs that you probably already know about them but I'm reporting them back just in case you don't.
1. For high latitudes values (close to 90) I get this error:
   Failed to load resource: https://maps.googleapis.com/maps/api/timezone/json?location=NaN,-122.398&timestamp=1461030020.884 the server responded with a status of 400 ()
2. open in new tab does not load the control tab correctly. Looks like it loads an old version of the control tab.

![image](https://cloud.githubusercontent.com/assets/2915573/14620896/6c521098-058d-11e6-95a3-9c8105aebe8e.png)

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> > > For high latitudes values (close to 90) I get this error:

This is a fun issue: Map tiles from Google/Open Street/etc only go to +-85.0511. See 

https://en.wikipedia.org/wiki/Tiled_web_map

and

http://wiki.osgeo.org/wiki/Tile_Map_Service_Specification

Eventually the error will be picked up and an error message will get into the code.

> > open in new tab does not load the control tab correctly. Looks like it loads an old version of the control tab.

Loading OBJ and JSON files is almost under control. I should be back on Sun paths - and issues like these- very soon.

But do remember that when software is being updated frequently you may need to clear the cache.

How to clear files in the cache:
1. Have the JavaScript console open.
2. Right-click the recycle icon in the Chrome menu. 
3. Dropdown appears
4. Click Hard reload

**Comment by mostaphaRoudsari** [comment]
@theo-armour thanks! I didn't know about hard reload. I'll give it a try.
