### ISSUE TITLE
Update ~ 2016-05-06 ~ Current Status

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#25]
##@ladybug-analysis-tools/owners 

Hi Team Ladybug

This weekend I am traveling to San Luis Obispo to visit my youngest daughter. So instead of coding, today is about cleaning up my desk and thinking about where we are going. 
### Designing an End-User Workflow

Between the scripts in the Ladybug Web and 3D Models repositories, there are the beginnings of an extensive bag of tools. But like any bag of tools there are tools that will never ever be used again and tools that will be used everyday, tools to help programmers and tools to help designers, and so on.

If the tool set is to actually become useful then we need to create a successful work flow that allows you to:
- Open or link to a 3D model
- Adjust parameters including
  - Latitude and longitude
  - Camera position and target
  - Model scale, position and rotation
  - Other parameters
- View the Sun position at any date and time
- View the shadow path for June 21 and December 21 - and any day in between
- Save the model and parameters somewhere so that there is a URL
- Share the link with clients and colleagues
  - And/or embed the linked to project in a report or web page

Next week - and along with any input - I will get a document like this on Ladybug Web and it can also be the beginning of the documentation.
### Questions

If we are to achieve a good workflow then a number of issues must be dealt with. So let me start with a few questions:
1. Is there a technical name of names for this full-day shadow path diagram I am still working on?
2. I assume the initial group of end-users will be existing Rhino/Grasshopper users. It is essential that the process of going from Rhino/Grasshopper files to files suitable for our work be as painless and as streamlined as possible. (The files that I have received so far have many issues.) Where can I find details and source code for Rhine/Grasshopper file exporters?
3. If we expect user to be able to share visualizations with clients and colleagues then the files must be available online. How do we anticipate end-users getting their files online and what cloud services do we expect users to be using to store files?

---

bye for now,

Theo

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour,

I try to answer to your questions to the best of my knowledge.
1. It's called shadow-range.
2. We have different options. @ayezioro can comment better about what he has used in his examples but two of the most possible options are [Iris](http://www.food4rhino.com/project/iris?ufh) and [Spectacles](https://github.com/tt-acm/Spectacles.GrasshopperExporter). The latter is a fork from va3c.
3. I think most of them will use dropbox, googledrive or github but again we will know more once we let people to try it! =)

Hope you enjoy your visit this weekend :sunny:

**Comment by ayezioro** [comment]
Hi,
One comment/wish about the shadow range. If possible will be VERY nice and usefull to let users define the hours to show. From my experience you use this analysis to check possibilities of using open spaces or facade exposure to sun. The whole day is not the most desired option (for me at least).
As for point 2 ... i don't know the sources for the export formats. Last time i used the Flux plugin for GH but seems that it didn't was so successful (json format).
Enjoy your WE.
-A.

**Comment by theo-armour** [comment]
@ayezioro 

> One comment/wish about the shadow range. If possible will be VERY nice and usefull to let users define the hours to show.

Very good point. I have added it to the wish list.

@mostaphaRoudsari 

> > source code for Rhine/Grasshopper file exporters?  
> > two of the most possible options are Iris and Spectacles.

The canonical test for Three.js JSON files is whether they can be viewed the Three.js editor

http://threejs.org/editor/

I have looked at files from both scripts and all the results have issues being loaded.

I have spent a number of hours trying to create internal work arounds so that incorrectly formatted files still load. You can see some results here:

https://ladybug-analysis-tools.github.io/3d-models/content/json/index.html

But it's all taking too many hours. So for the moment I have stopped progressing the JSON work and am concentrating on OBJ/MTL files. 

I can continue to work with JSON but I will need to be in contact with Ben Howes and Luis at McNeel to see if they will offer to make some updates to their scripts to make the results more compatible before I continue with try to read their results.

.

**Comment by mostaphaRoudsari** [comment]
> The canonical test for Three.js JSON files is whether they can be viewed the Three.js editor
> http://threejs.org/editor/

@theo-armour I agreed! Should we just mention Ben and Luis here in github or do you want to send them an email?

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> Should we just mention Ben and Luis here in github or do you want to send them an email?

If we have to wait for other peeps too fix things before our apps work, then this is not fun.

We know that OBJ and MTL files work. And so can STL, ASCII FBX and other types.

So my first response is:

**Are there tools for exporting OBJ and MTL (or STL or other popular 3D formats ) files from Rhino?**

Secondly - and eventually - I plan to contact Luis and Ben. If they - or you - see a need for speedy action then, of course, I will jump on the case. But for the moment the priority should be seeking sources of files that conform to standard now and that we can use to build demos of what we now have working. 

Does that make sense?

**Comment by mostaphaRoudsari** [comment]
> Does that make sense?

Yes! totally.
