### ISSUE TITLE
Update ~ 2016-06-07 ~ Shadow Range OBJ Opener R1 & More

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#31]
![image](https://cloud.githubusercontent.com/assets/547626/15871740/0675c73e-2cab-11e6-88c6-0a412f8c24fd.png)
_Silly things you can to with Ladybug WebShadow Range OBJ Opener_

@ladybug-analysis-tools/owners @ayezioro 

The shadow range files have been up for a week. Anybody had a look?

If you have not, then start with Gallery. 

Core is quite stable - but there's not much to interact with - since it's just the 'engine' that other scripts can use. Opener is still a bit flaky - too sensitive when you try to update position and rotation parameters. Also still missing a bunch of parameters that Gallery has.

The WebGL crashes I will be working on so no need to mention these. When there is a WebGL crash all you need to do is refresh the page. Nothing is harmed in the process - except my pride.

There's still much to be done on the documentation. Have a look at [Ladybug Web Analemma 3D Read Me](https://ladybug-analysis-tools.github.io/ladybug-web/analemma-3d/index.html#readme.md) to see where things are going.

What I would like to hear about includes where you think the user experience is failing and what might be done to make these scripts usable in a practice.

See also the previous update for more thoughts #29 

---
## [Ladybug Web Shadow OBJ Core](https://ladybug-analysis-tools.github.io/ladybug-web/shadow-obj-core/)
- The 'engine' that does all the Three.js
## [Ladybug Web Shadow Range OBJ Opener](https://ladybug-analysis-tools.github.io/ladybug-web/shadow-range-obj-opener/)
- The editor
## [Ladybug Web Shadow Range OBJ Gallery](https://ladybug-analysis-tools.github.io/ladybug-web/shadow-range-obj-gallery/)
- The viewer
### Recent updates
- Tweak code and fix errors
- Update read me files to include images and iframes

**Comment by mostaphaRoudsari** [comment]
@theo-armour, I think most of the people will be interested in Shadow Range OBJ Gallery. I just wrote my comment under another issue.

Do you think that this is the right time to add more people to test the development? I personally think that's the best way to know what is working and what is not and what would be the most critical next steps.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Sorry for the delay in replying.

> Do you think that this is the right time to add more people to test the development?

We're nearly there. Gallery and Opener both need a few more bit added to their menus and then we are good to go. Fingers crossed it's all in the next status update.

**Comment by mostaphaRoudsari** [comment]
Perfect! We have a couple of other releases coming soon and I don't want this one to get lost among them. We has a better experience of introducing new developments one by one.
