### ISSUE TITLE
Update ~ 2016-06-16 ~ Ladybug Web Shadow Range OBJ Core R3

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#32]
![image](https://cloud.githubusercontent.com/assets/547626/16139094/2be7e97a-33f9-11e6-9847-7e13d8280e6f.png)

@ladybug-analysis-tools/owners @ayezioro 

_Addresses Moustapha's comment in #29 and beginning to look pretty_
## Change Log
- Update read me with permalink/location hash parameters
- Fix display of sun positions in menu
- Add to and edit location hash parameters
  - Add set number of minutes between sun positions
    - Addresses Moustapha's comment in #29 
  - Add toggle helpers
  - Add toggle placards
- Add display of yellow spheres as suns
- Add placards above tee suns with time display

Note that [Ladybug Web Shadow Range OBJ Opener ](https://ladybug-analysis-tools.github.io/ladybug-web/shadow-range-obj-opener/) and [Ladybug Web Shadow Range OBJ Gallery ](https://ladybug-analysis-tools.github.io/ladybug-web/shadow-range-obj-gallery/) are automatically updated as a well since they rely on core for all Three.js operations.

**Comment by ayezioro** [comment]
This looks very pretty!!
Probably you know, but i'm seeing something weird with the sun positions and the time shown . In the above picture 9:00 is at the left of the path. Like the position is inverted. Can be?
Also the axis lines are not in sync withe north?
I'm looking wrong?
Thanks,
-A.

**Comment by theo-armour** [comment]
@ayezioro 

> I'm looking wrong?

I tricked you! ;-)

Look at the menu:

> > Latitude:-33.000
> > Longitude:151.000
> > 
> > Currently:
> > Sun azimuth:56
> > Sun altitude:7
> > 
> > Time Zone ID: Australia/Sydney
> > Time zone: Australian Eastern 
> 
> Also the axis lines are not in sync with north?

The axis are traditional computer graphcs style

X = right, Y = up, Z = out the screen.

I will be adding a traditional north point sign - and will add this to the wish list

**Comment by ayezioro** [comment]
You are right about the sunpath location :-)
About the axis still doesn't make sense for me, at least for the specific model. Let's assume the north is up (towards the sunpath suns). The blue axis should point right (or left) and the red should point up (or down accordingly).
Is like the north is rotated in relation to the model (or the model in relation to the north).
Makes sense?
-A.

**Comment by theo-armour** [comment]
@ayezioro 

> About the axis still doesn't make sense for me, at least for the specific model.

Ignore the axis. Sorry about the confusion. The axis represents the XYZ cartesian coordinates. The XYZ of the model has nothing/zero/nada to do with North and South. It helps with debugging. In a future release I will be adding a north arrow.

**Comment by mostaphaRoudsari** [comment]
@theo-armour does it mean that the north arrow is in the reversed direction on the blue axis? otherwise @ayezioro's comment makes sense that the sun positions can be reversed!

It's beautiful though. I love it! :D

**Comment by theo-armour** [comment]
Thanks for the kind words!
