### ISSUE TITLE
Update ~ 2016-06-26 ~ a variety of small updates

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#36]
@ladybug-analysis-tools/owners 

Quite a bit of work on Analemma 3D - but just because I had worked on it yesterday. My main priority is now on the three Shadow Range OBJ scripts. Progress today was gentle and ongoing.

Opener needs a lot of cleaning up, but is getting there.

The main outstanding work is completing the read me files for each script.

Note!
In every script you can click on the 'i in a circle' info icon to jump straight to its read me file.

Another read me file to look at is:

[Ladybug Web Project Explorer](https://ladybug-analysis-tools.github.io/ladybug-web/)

---
## [Analemma 3D R16](https://ladybug-analysis-tools.github.io/ladybug-web/analemma-3d/)
- Update read me
- Add intensity of Sun light slider
- Add auto-rotate
- Update menu wording
- Add auto-rotate with check box toggle
- Sun is now bright yellow
- Default location displays properly
- Add turn off casting and receiving of shadows whenever the sun is below the ground plane/horizon.
## [Ladybug Web Shadow Range OBJ Opener R2](https://ladybug-analysis-tools.github.io/ladybug-web/shadow-range-obj-opener/)
- Menu mostly complete and operational
## [Ladybug Web Shadow Range OBJ Gallery R5](https://ladybug-analysis-tools.github.io/ladybug-web/shadow-range-obj-gallery/)
- Improve auto-rotate behavior
- Add to read me

**Comment by mostaphaRoudsari** [comment]
@theo-armour you're a natural teacher. This is very educational. Thanks!
