### ISSUE TITLE
2016-07-13 ~ Analemma 3D R18 'What time is it, Ben?'

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#42]
@ladybug-analysis-tools/owners @art 

Thank you, Art, for the fun suggestion.

Analemma 3D is now a working virtual sun dial!

You will note this because the minute slider bar updates every minute and the Big Ben chimes are played every quarter hour (only when the tab is visible though).

So this kicks off many thoughts on what: should the clock of the future show or tell you?
## \* Change Log 2016-07-13 ~ R18
- Adds update the time every minute
- Add play appropriate Westminster chime on the quarter hour
  - No hourly bongs yet
  - No way to turn off sound yet
    - Will only update if tab is visible

**Comment by mostaphaRoudsari** [comment]
@theo-armour sounds really fun. For some reason I couldn't get the bell to ring.

Also when I update the hour and location the yellow band doesn't update.

![image](https://cloud.githubusercontent.com/assets/2915573/17157154/42d18c56-5396-11e6-94b6-487f96db56ff.png)

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

Probable issue: the chimes only sound at the 15 minute mark and if the tab is visible. I will add that says: 'ring the bell' ;-)

Yup hello band has an issue. Noted in read me.

I am currently working on an objectified .is version that thatadd an analemma to almost any Three.js scene. The band will be fixed in that revision.
