### ISSUE TITLE
Ladybog Analysis Tools Home Page

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/ladybug-web#7]
Currently the main link goes to a 404 error:

https://ladybug-analysis-tools.github.io

I would be happy to set up a simple home page here.

Either somebody can:
- Create a repo titled - exactly: 'ladybug-analysis-tools.github.io' and give me access

Or
- Give me authority to create repos

Once the repo is set up, it would be nice to have access to the Ladybug images there so we can add these to web pages and add favicons.

No hurry, Whenever is OK.

Theo

**Comment by mostaphaRoudsari** [comment]
Done! Created the repository and added you as an admin.
https://github.com/ladybug-analysis-tools/ladybug-analysis-tools.github.io
